### PR TITLE
backbone-collection-proxy dependency missing from bower.json

### PR DESCRIPTION
**Pull request by apaleslimghost**

### CODE REVIEW

**Comment by jmorrell** [comment]
Thanks for the PR, but `backbone-collection-proxy` isn't actually a dependency for bower since bower points to the [UMD built version](https://github.com/jmorrell/backbone-filtered-collection/blob/master/backbone-filtered-collection.js) which includes `backbone-collection-proxy`. The only dependencies here are backbone and underscore.

Did you come across some issue trying to use bower?

**Comment by apaleslimghost** [comment]
The standalone version didn't work with Browserify for me. It still contains calls to `require` for bundled modules, which Browserify parses and can't find. [Derequire](https://github.com/calvinmetcalf/derequire) can get rid of these.

**Comment by jmorrell** [comment]
Any particular reason you're using browserify with bower and not npm? I was working under the assumption that bower users would be using AMD or script includes.

If adding a dependency solves your problem, I'm happy to add it to the `bower.json` file, but I suspect that's not going to be quite right either. Derequire seems like it might be a good solution, but I'm not sure I want to go messing with a build system in a module I consider pretty much "done".

**Comment by apaleslimghost** [comment]
My app uses several dependencies that are only on Bower. It's less maintenance overhead to have everything just in bower.json.

**Comment by jmorrell** [comment]
@quarterto I updated the build system to use the same one I'm using in [Obscura](https://github.com/jmorrell/backbone.obscura), which mangles the require statement like derequire. Give 0.4.0 a try.

**Comment by apaleslimghost** [comment]
no longer using this lib, but thanks anyway.

**Pull request closed without merging**
